# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16cb38121fee427fed4fa9228d3cf215da6ea0f2bea5289b4fbbd674580f8d3ac6b5afdc3d1049a3cbc27499049e292bc03e7910531690a31272c74cf9e9f9ee

test:
  secret_key_base: d4a5142910fd42b6323226556c93402cec03fc6adbaed69a0b74e15b861542066e53238e8f582c9d1a1cd2040d7f6948436572aef9bef82c050cabe118405afd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
